export enum COLORS {
  WHITE = '#FFFFFF',
  BLACK = '#000000',
  ERROR = '#B00020',
  GREY_700 = '#6B6B6B',
  BLUE_700 = '#273B7A',
}

export enum colors {
  WHITE = COLORS.WHITE,
  BLACK = COLORS.BLACK,

  PRIMARY = COLORS.BLUE_700,

  BACKGROUND = COLORS.WHITE,

  SURFACE = COLORS.WHITE,

  TEXT_COLOR = COLORS.WHITE,
  SECONDARY_TEXT_COLOR = COLORS.GREY_700,
  ERROR = COLORS.ERROR,
}
