enum COLORS {
  WHITE = '#FFFFFF',
  BLACK = '#000000',
}

export enum colors {
  'PRIMARY' = COLORS.BLACK,
  'PRIMARY_LIGHT' = COLORS.BLACK,
  'PRIMARY_DARK' = COLORS.BLACK,

  'SECONDARY' = COLORS.WHITE,
  'SECONDARY_LIGHT' = COLORS.WHITE,
  'SECONDARY_DARK' = COLORS.WHITE,

  'BACKGROUND' = COLORS.WHITE,

  'SURFACE' = COLORS.WHITE,

  'ERROR' = COLORS.WHITE,
}
