export enum COLORS {
  WHITE = '#FFFFFF',
  BLACK = '#000000',
  ERROR = '#B00020',
  GREY_700 = '#6B6B6B',
  BLUE_700 = '#273B7A',
  BLUE_900 = '#18285c',
}

export enum colors {
  WHITE = COLORS.WHITE,
  BLACK = COLORS.BLACK,

  PRIMARY = COLORS.BLUE_700,
  PRIMARY_DARK = COLORS.BLUE_900,

  BACKGROUND = COLORS.WHITE,

  SURFACE = COLORS.WHITE,

  TEXT_COLOR = COLORS.BLACK,
  SECONDARY_TEXT_COLOR = COLORS.GREY_700,
  TEXT_ON_PRIMARY = COLORS.WHITE,
  ERROR = COLORS.ERROR,
}
